### ISSUE TITLE
...How do you actually pair the device to set up the integration?

### ISSUE THREAD

**Issue by emmawinston** [d03n3rfr1tz3/hass-divoom#15]
I am stumped! This looks like exactly what I need, but I can't get to the point of actually setting up the integration, because it seems impossible to pair the Pixoo to the Home Assistant. 

I'm running Home Assistant on RPi so hciconfig isn't available and I'm using bluetoothctl instead.

I can find the MAC address of the Pixoo using bluetoothctl, but trying to pair with it seems to cause a crash which disables bluetooth until the Pi is rebooted. 

I assumed there was some sort of non-standard pairing protocol on the Pixoo, since it can't be paired to directly from a mobile device either and has to be paired through the Divoom app...but the docs for this project suggest I should be able to just pair with it directly once I have the MAC address. 

(As you may be able to tell, I know very little about bluetooth.)

Am I missing something? Has anyone else had this problem?

**Comment by wchorski** [comment]
So you're saying the native HA Bluetooth integration doesn't pick up the pixoo?

try dropping this into your HA `configuration.yml`

```yml
notify:
  - name: pixoo
    platform: divoom
    mac: "11:75:58:5E:D5:D7" # <---- your pixoo MAC address.
    device_type: "pixoo"
    media_directory: "pixelart"
```

also turn off you're phone (or any device connected to the Pixoo) and turn on the pixoo device. Does a blue Bluetooth symbol flash on the screen during boot? If so Then the connection to your RPi is being made
